FROM node:18.16-alpine3.16
WORKDIR /app

# COPY package.json and package-lock.json files
COPY package*.json ./

# generated prisma files
COPY prisma ./prisma/

# COPY ENV variable
COPY .env ./

# COPY tsconfig.json file
COPY tsconfig.json ./

# COPY
COPY . .

RUN npm install
RUN npx prisma generate
RUN npm install pm2 -g
RUN npx tsc
EXPOSE 3001
CMD [ "pm2-runtime", "ecosystem.config.js"]